BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.SREPI_Reservas_Log', 'XP_Otorgada') IS NULL
    BEGIN
        ALTER TABLE dbo.SREPI_Reservas_Log
        ADD XP_Otorgada INT NOT NULL CONSTRAINT DF_SREPI_Reservas_Log_XP DEFAULT (0);
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
